# Generated by Django 3.2.3 on 2025-07-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'избранные'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'verbose_name': 'Список покупок', 'verbose_name_plural': 'Списки покупок'},
        ),
        migrations.RemoveConstraint(
            model_name='favorites',
            name='unique_user_favorite_recipe',
        ),
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='unique_user_shopping_recipe',
        ),
    ]
