# Generated by Django 3.2.3 on 2025-05-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipes_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipesingredients',
            old_name='quantity',
            new_name='amount',
        ),
    ]
