# Generated by Django 3.2.3 on 2025-06-06 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20250604_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=32, verbose_name='ссылка')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_link', to='recipes.recipes')),
            ],
            options={
                'verbose_name': 'Короткая ссылка',
                'verbose_name_plural': 'короткие ссылки',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='links',
            constraint=models.UniqueConstraint(fields=('recipe', 'link'), name='Recipe unique link'),
        ),
    ]
