# Generated by Django 3.2.3 on 2025-07-01 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20250606_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['id'], 'verbose_name': 'Тег', 'verbose_name_plural': 'теги'},
        ),
        migrations.AlterField(
            model_name='recipesingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_recipe', to='recipes.ingredients', verbose_name='Ингредиент'),
        ),
    ]
