# Generated by Django 3.2.3 on 2025-05-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250529_0815'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Subscriptions',
        ),
    ]
