# Generated by Django 3.2.3 on 2025-06-06 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20250531_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['id'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'ordering': ['id']},
        ),
    ]
